language: go

go:
  - 1.11.x
  - 1.12.x
  
env:
  - GO111MODULE=on

install: true
#  - go build .
#  - dep ensure

script:
  - go build .
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
